[package]
name = "argparse"
version = "0.1337.0"
edition = "2021"
authors = ["Joshua"]

[dependencies]
access_log_parser = "0.9.0"
anyhow = "1.0.93"
chrono = "0.4.38"
clap = { version = "4.5.21", features = ["derive"] }
